image:
  name: "python:3.11"
  pull_policy: if-not-present
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/
before_script:
  - python3 --version
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install -r compile/requirements.txt
  - mkdir -p .output

stages:
  - compile



compile:
  tags:
  - group_runner_spraaksamlingene_01
  script:
    - python compile/md2vue.py
  artifacts:
    paths:
      - .output/


